// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCsBxv2HoZWdJZZFJE4_bH355RZYlwbpUE',
    appId: '1:677529446190:web:ab9abfeb4a9274a0d4bcbf',
    messagingSenderId: '677529446190',
    projectId: 'test-86a04',
    authDomain: 'test-86a04.firebaseapp.com',
    storageBucket: 'test-86a04.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC19qoyzJhS9MeEB_UAXsiVjpIPRA29T3U',
    appId: '1:677529446190:android:8a874e8b800a1fced4bcbf',
    messagingSenderId: '677529446190',
    projectId: 'test-86a04',
    storageBucket: 'test-86a04.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD_PFffv-N-_0dS7iOO7n2lgqZMclmZ79Q',
    appId: '1:677529446190:ios:a203305260371dc3d4bcbf',
    messagingSenderId: '677529446190',
    projectId: 'test-86a04',
    storageBucket: 'test-86a04.appspot.com',
    iosClientId: '677529446190-hsptmq64ngmkughdppr94g8lpip17uoj.apps.googleusercontent.com',
    iosBundleId: 'com.example.testFirebase',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD_PFffv-N-_0dS7iOO7n2lgqZMclmZ79Q',
    appId: '1:677529446190:ios:60b93e44effa2af2d4bcbf',
    messagingSenderId: '677529446190',
    projectId: 'test-86a04',
    storageBucket: 'test-86a04.appspot.com',
    iosClientId: '677529446190-25i8u28ajv5qdpie64fuanolvc3uj2po.apps.googleusercontent.com',
    iosBundleId: 'com.example.testFirebase.RunnerTests',
  );
}
